// <auto-generated />
using System;
using Imi.Project.Herexamen.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imi.Project.Herexamen.Api.Infrastucture.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220807144340_TableNameErrorFix")]
    partial class TableNameErrorFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.CombatRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CombatRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "The spine of the infantry and fist of the squad, the rifleman is equipped with a standard select-fire service rifle to carry out the offensive and defensive orders of their squad leader.",
                            Name = "Rifleman"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Provides overwatch and suppresive fire for his teammates through high firepower. Usually equipped with a belt-fed light machine gun to maximize combat efficiency.",
                            Name = "Autorifleman"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "A rifleman that specialises in the use of grenades and other explosives to provide high-angle fire over deadzones. Equiped with either a rifle or carabine fitted with an 40mm under-barrel grenade launcher",
                            Name = "Grenadier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "An infantryman skilled in precision firepower at longer-than-usual ranges. Usually kitted with a DMR (Designated Marksman Rifle), a long-range version of typical assault rifles. Sometimes carries out reconnaissance tasks within the squad.",
                            Name = "Scout"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "A medically trained rifleman who's role is to provide emergency treatment to those wounded on the battlefield, friend or foe. Deployed to the front line within a regular fire team and armed as a regular rifleman, but expected to stay out of direct-fire lines to focus on treating those in need.",
                            Name = "Combat Medic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "Infantryman kitted with various anti-tank equipment to counter the threat of enemy armor. Loadouts usually include a carbine-style primary weapon, an launcher of recoilless rifle with AT-munitions and AT-mines.",
                            Name = "AT Specialist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "A squadmate that provides engineering tasks in the AO, be it construction or demolition. Equipped with a standard rifleman's loadout supplemented with various tools to carry out his tasks.",
                            Name = "Combat Engineer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Marksman who engages targets from positions of concealment, usually from out of the direct vincinity of his squadmates. Equipped with a long-range high-precision rifle with high-magnification optics.",
                            Name = "Sniper"
                        });
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Altis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Stratis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Malden"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Tanoa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Chernarus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Isla Duala"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Bystrica"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Sahrani"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Tembelan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Vidda"
                        });
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sitrep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZeroHour")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CodeName = "Blackout",
                            MapId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 4, 1, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CodeName = "Homesick",
                            MapId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 4, 8, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CodeName = "Night Spear",
                            MapId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 4, 16, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CodeName = "Dangerous Places",
                            MapId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 4, 24, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CodeName = "Last Flight",
                            MapId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 4, 30, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CodeName = "Last Flight Night",
                            MapId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 5, 5, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CodeName = "Half-Life",
                            MapId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 5, 14, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CodeName = "Hellish Politics",
                            MapId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 5, 21, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CodeName = "Knock Knock",
                            MapId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 5, 27, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CodeName = "Nexus",
                            MapId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 1, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CodeName = "New Wind",
                            MapId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 8, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CodeName = "Blackjack",
                            MapId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 14, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CodeName = "Dragon's Tail",
                            MapId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 20, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CodeName = "Apex Predator",
                            MapId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 24, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CodeName = "Anvil",
                            MapId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 6, 29, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CodeName = "White Christmas",
                            MapId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2021, 12, 21, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CodeName = "Knife's Edge",
                            MapId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 1, 3, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CodeName = "FUBAR",
                            MapId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 1, 14, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CodeName = "Lion's Den",
                            MapId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 1, 20, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CodeName = "Vulture",
                            MapId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Sitrep = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo ante sit amet semper lacinia. Duis sit amet ante non tellus maximus finibus a non libero. Pellentesque ac tempor tortor, id hendrerit arcu. Duis nec sem urna. Sed at viverra odio. Pellentesque molestie mauris feugiat odio tristique vulputate. Cras sit amet neque elementum, faucibus arcu vel, finibus libero. Nullam non lacus eu dui blandit condimentum. Sed in justo eget magna gravida faucibus efficitur laoreet ligula. Etiam vel tincidunt tortor. Aenean quis sem mattis, dignissim purus ut, consequat lacus.",
                            ZeroHour = new DateTime(2022, 1, 29, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.Participation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("Participation");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            OperationId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CombatRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("SquadLeader")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CombatRoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SquadLeader = true,
                            Username = "HOX"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000006"),
                            SquadLeader = true,
                            Username = "ChristianVoo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SquadLeader = false,
                            Username = "HollowPointsz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SquadLeader = false,
                            Username = "IMrByBy3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SquadLeader = true,
                            Username = "Brangers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SquadLeader = true,
                            Username = "PetrolHeadG98"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000005"),
                            SquadLeader = false,
                            Username = "Kwatman"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            SquadLeader = false,
                            Username = "Tokoshi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SquadLeader = false,
                            Username = "Aidan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CombatRoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SquadLeader = false,
                            Username = "Tiski"
                        });
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.Operation", b =>
                {
                    b.HasOne("Imi.Project.Herexamen.Api.Core.Models.Map", "Map")
                        .WithMany("Operations")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.Participation", b =>
                {
                    b.HasOne("Imi.Project.Herexamen.Api.Core.Models.Operation", "Operation")
                        .WithMany("Participations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imi.Project.Herexamen.Api.Core.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imi.Project.Herexamen.Api.Core.Models.User", b =>
                {
                    b.HasOne("Imi.Project.Herexamen.Api.Core.Models.CombatRole", "CombatRole")
                        .WithMany("Users")
                        .HasForeignKey("CombatRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
